#loc = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":10:0)
#loc21 = loc("a_ptr"(#loc))
#loc22 = loc("c_ptr"(#loc))
#loc23 = loc("M"(#loc))
#loc24 = loc("N"(#loc))
#loc25 = loc("stride_am"(#loc))
#loc26 = loc("stride_cm"(#loc))
module {
  tt.func public @wrap_stacked(%a_ptr: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("a_ptr"(#loc)), %c_ptr: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("c_ptr"(#loc)), %M: i32 loc("M"(#loc)), %N: i32 loc("N"(#loc)), %stride_am: i32 loc("stride_am"(#loc)), %stride_cm: i32 loc("stride_cm"(#loc))) attributes {noinline = false} {
    %c1_i32 = arith.constant 1 : i32 loc(#loc1)
    %c2_i32 = arith.constant 2 : i32 loc(#loc1)
    %c0_i32 = arith.constant 0 : i32 loc(#loc1)
    %cst = arith.constant dense<4> : tensor<4x4xi32> loc(#loc2)
    %offs_am = arith.constant dense<2> : tensor<4xi32> loc(#loc27)
    %offs_am_0 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32> loc(#loc28)
    %offs_am_1 = arith.addi %offs_am_0, %offs_am : tensor<4xi32> loc(#loc27)
    %offs_am_2 = tt.splat %M : i32 -> tensor<4xi32> loc(#loc29)
    %offs_am_3 = arith.remsi %offs_am_1, %offs_am_2 : tensor<4xi32> loc(#loc29)
    %a_ptrs = tt.expand_dims %offs_am_3 {axis = 1 : i32} : tensor<4xi32> -> tensor<4x1xi32> loc(#loc30)
    %a_ptrs_4 = tt.splat %stride_am : i32 -> tensor<4x1xi32> loc(#loc31)
    %a_ptrs_5 = arith.muli %a_ptrs, %a_ptrs_4 : tensor<4x1xi32> loc(#loc31)
    %a_ptrs_6 = tt.expand_dims %offs_am_0 {axis = 0 : i32} : tensor<4xi32> -> tensor<1x4xi32> loc(#loc32)
    %a_ptrs_7 = tt.broadcast %a_ptrs_5 : tensor<4x1xi32> -> tensor<4x4xi32> loc(#loc33)
    %a_ptrs_8 = tt.broadcast %a_ptrs_6 : tensor<1x4xi32> -> tensor<4x4xi32> loc(#loc33)
    %a_ptrs_9 = arith.addi %a_ptrs_7, %a_ptrs_8 : tensor<4x4xi32> loc(#loc33)
    %a_ptrs_10 = tt.splat %a_ptr : !tt.ptr<f32> -> tensor<4x4x!tt.ptr<f32>> loc(#loc34)
    %a_ptrs_11 = tt.addptr %a_ptrs_10, %a_ptrs_9 : tensor<4x4x!tt.ptr<f32>>, tensor<4x4xi32> loc(#loc34)
    %c_ptrs = tt.expand_dims %offs_am_0 {axis = 1 : i32} : tensor<4xi32> -> tensor<4x1xi32> loc(#loc35)
    %c_ptrs_12 = tt.splat %stride_cm : i32 -> tensor<4x1xi32> loc(#loc36)
    %c_ptrs_13 = arith.muli %c_ptrs_12, %c_ptrs : tensor<4x1xi32> loc(#loc36)
    %c_ptrs_14 = tt.splat %c_ptr : !tt.ptr<f32> -> tensor<4x1x!tt.ptr<f32>> loc(#loc37)
    %c_ptrs_15 = tt.addptr %c_ptrs_14, %c_ptrs_13 : tensor<4x1x!tt.ptr<f32>>, tensor<4x1xi32> loc(#loc37)
    %c_ptrs_16 = tt.broadcast %c_ptrs_15 : tensor<4x1x!tt.ptr<f32>> -> tensor<4x4x!tt.ptr<f32>> loc(#loc38)
    %c_ptrs_17 = tt.addptr %c_ptrs_16, %a_ptrs_8 : tensor<4x4x!tt.ptr<f32>>, tensor<4x4xi32> loc(#loc38)
    %c_ptrs_18:2 = scf.for %k = %c0_i32 to %c2_i32 step %c1_i32 iter_args(%a_ptrs_19 = %a_ptrs_11, %c_ptrs_20 = %c_ptrs_17) -> (tensor<4x4x!tt.ptr<f32>>, tensor<4x4x!tt.ptr<f32>>)  : i32 {
      %a = tt.load %a_ptrs_19 : tensor<4x4x!tt.ptr<f32>> loc(#loc40)
      tt.store %c_ptrs_20, %a : tensor<4x4x!tt.ptr<f32>> loc(#loc16)
      %a_ptrs_21 = tt.addptr %a_ptrs_19, %cst : tensor<4x4x!tt.ptr<f32>>, tensor<4x4xi32> loc(#loc41)
      %c_ptrs_22 = tt.addptr %c_ptrs_20, %cst : tensor<4x4x!tt.ptr<f32>>, tensor<4x4xi32> loc(#loc42)
      scf.yield %a_ptrs_21, %c_ptrs_22 : tensor<4x4x!tt.ptr<f32>>, tensor<4x4x!tt.ptr<f32>> loc(#loc19)
    } loc(#loc43)
    tt.return loc(#loc20)
  } loc(#loc)
} loc(#loc)
#loc1 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":19:22)
#loc2 = loc(unknown)
#loc3 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":11:19)
#loc4 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":11:32)
#loc5 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":11:38)
#loc6 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":13:30)
#loc7 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":13:41)
#loc8 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":13:61)
#loc9 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":13:53)
#loc10 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":13:22)
#loc11 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":17:41)
#loc12 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":17:33)
#loc13 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":17:21)
#loc14 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":17:52)
#loc15 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":20:20)
#loc16 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":21:25)
#loc17 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":22:18)
#loc18 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":23:18)
#loc19 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":23:8)
#loc20 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_modulo.py":19:4)
#loc27 = loc("offs_am"(#loc3))
#loc28 = loc("offs_am"(#loc4))
#loc29 = loc("offs_am"(#loc5))
#loc30 = loc("a_ptrs"(#loc6))
#loc31 = loc("a_ptrs"(#loc7))
#loc32 = loc("a_ptrs"(#loc8))
#loc33 = loc("a_ptrs"(#loc9))
#loc34 = loc("a_ptrs"(#loc10))
#loc35 = loc("c_ptrs"(#loc11))
#loc36 = loc("c_ptrs"(#loc12))
#loc37 = loc("c_ptrs"(#loc13))
#loc38 = loc("c_ptrs"(#loc14))
#loc39 = loc("a_ptrs"(#loc1))
#loc40 = loc("a"(#loc15))
#loc41 = loc("a_ptrs"(#loc17))
#loc42 = loc("c_ptrs"(#loc18))
#loc43 = loc("c_ptrs"(#loc39))
