#loc = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":11:0)
#loc13 = loc("in0"(#loc))
#loc14 = loc("out0"(#loc))
#loc15 = loc("mask_bound"(#loc))
module {
  tt.func public @addptr_with_masks(%in0: !tt.ptr<i32> {tt.divisibility = 16 : i32} loc("in0"(#loc)), %out0: !tt.ptr<i32> {tt.divisibility = 16 : i32} loc("out0"(#loc)), %mask_bound: i32 loc("mask_bound"(#loc))) attributes {noinline = false} {
    %c1_i32 = arith.constant 1 : i32 loc(#loc1)
    %c4_i32 = arith.constant 4 : i32 loc(#loc1)
    %c0_i32 = arith.constant 0 : i32 loc(#loc1)
    %cst = arith.constant dense<4> : tensor<4xi32> loc(#loc2)
    %cst_0 = arith.constant dense<-11> : tensor<4xi32> loc(#loc2)
    %offs = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32> loc(#loc16)
    %mask = tt.splat %mask_bound : i32 -> tensor<4xi32> loc(#loc17)
    %a = tt.splat %in0 : !tt.ptr<i32> -> tensor<4x!tt.ptr<i32>> loc(#loc18)
    %0 = tt.splat %out0 : !tt.ptr<i32> -> tensor<4x!tt.ptr<i32>> loc(#loc6)
    %out_offs:2 = scf.for %i = %c0_i32 to %c4_i32 step %c1_i32 iter_args(%offs_1 = %offs, %out_offs_2 = %offs) -> (tensor<4xi32>, tensor<4xi32>)  : i32 {
      %mask_3 = arith.cmpi slt, %offs_1, %mask : tensor<4xi32> loc(#loc17)
      %a_4 = tt.addptr %a, %offs_1 : tensor<4x!tt.ptr<i32>>, tensor<4xi32> loc(#loc18)
      %a_5 = tt.load %a_4, %mask_3, %cst_0 : tensor<4x!tt.ptr<i32>> loc(#loc20)
      %1 = tt.addptr %0, %out_offs_2 : tensor<4x!tt.ptr<i32>>, tensor<4xi32> loc(#loc6)
      tt.store %1, %a_5 : tensor<4x!tt.ptr<i32>> loc(#loc8)
      %offs_6 = arith.addi %offs_1, %cst : tensor<4xi32> loc(#loc21)
      %out_offs_7 = arith.addi %out_offs_2, %cst : tensor<4xi32> loc(#loc22)
      scf.yield %offs_6, %out_offs_7 : tensor<4xi32>, tensor<4xi32> loc(#loc11)
    } loc(#loc23)
    tt.return loc(#loc12)
  } loc(#loc)
} loc(#loc)
#loc1 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":19:22)
#loc2 = loc(unknown)
#loc3 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":12:24)
#loc4 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":20:22)
#loc5 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":21:26)
#loc6 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":22:24)
#loc7 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":21:20)
#loc8 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":22:34)
#loc9 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":23:16)
#loc10 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":24:20)
#loc11 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":24:8)
#loc12 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_tensor_index_iterargs.py":19:4)
#loc16 = loc("offs"(#loc3))
#loc17 = loc("mask"(#loc4))
#loc18 = loc("a"(#loc5))
#loc19 = loc("offs"(#loc1))
#loc20 = loc("a"(#loc7))
#loc21 = loc("offs"(#loc9))
#loc22 = loc("out_offs"(#loc10))
#loc23 = loc("out_offs"(#loc19))
