#loc = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_scalar_store.py":8:0)
#loc9 = loc("output_ptr"(#loc))
module {
  tt.func public @reduce_kernel_2d(%output_ptr: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("output_ptr"(#loc))) attributes {noinline = false} {
    %c8_i32 = arith.constant 8 : i32 loc(#loc1)
    %c0_i32 = arith.constant 0 : i32 loc(#loc1)
    %c1_i32 = arith.constant 1 : i32 loc(#loc2)
    %pid0 = tt.get_program_id x : i32 loc(#loc10)
    %base_ptr = tt.addptr %output_ptr, %pid0 : !tt.ptr<f32>, i32 loc(#loc11)
    %base_ptr_0 = scf.for %i = %c0_i32 to %c8_i32 step %c1_i32 iter_args(%base_ptr_1 = %base_ptr) -> (!tt.ptr<f32>)  : i32 {
      %0 = arith.sitofp %i : i32 to f32 loc(#loc5)
      tt.store %base_ptr_1, %0 : !tt.ptr<f32> loc(#loc5)
      %base_ptr_2 = tt.addptr %base_ptr_1, %c1_i32 : !tt.ptr<f32>, i32 loc(#loc13)
      scf.yield %base_ptr_2 : !tt.ptr<f32> loc(#loc7)
    } loc(#loc12)
    tt.return loc(#loc8)
  } loc(#loc)
} loc(#loc)
#loc1 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_scalar_store.py":14:22)
#loc2 = loc(unknown)
#loc3 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_scalar_store.py":12:25)
#loc4 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_scalar_store.py":13:28)
#loc5 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_scalar_store.py":16:27)
#loc6 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_scalar_store.py":17:20)
#loc7 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_scalar_store.py":17:8)
#loc8 = loc("/home/ubuntu/zwr/DLCompiler/third_party/wafer/examples/test_scalar_store.py":14:4)
#loc10 = loc("pid0"(#loc3))
#loc11 = loc("base_ptr"(#loc4))
#loc12 = loc("base_ptr"(#loc1))
#loc13 = loc("base_ptr"(#loc6))
