name: DLCompiler format ci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    if: github.repository == 'DeepLink-org/DLCompiler'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 16
    - name: Collect changed files
      uses: tj-actions/changed-files@v40
      id: changed-files
      with:
        files: '**/*.md'
        separator: ','
    - name: MarkdownLint
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: DavidAnson/markdownlint-cli2-action@v14
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ','

  clang-format:
    needs: markdownlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-17

      - name: Check changed files
        run: |
          git diff --diff-filter=d --name-only \
            origin/${{ github.base_ref }}...HEAD \
            > all_changed_files.txt

          awk '/\.(cc|cpp|cxx|h|hpp)$/ && $0 !~ /^third_party\// { print }' \
            all_changed_files.txt \
            > changed_files.txt

          if [ ! -s changed_files.txt ]; then
            echo "No C/C++ files changed"
            exit 0
          fi

          xargs -a changed_files.txt clang-format-17 --dry-run -Werror

  python-black:
    needs: markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保能获取到 main 分支的历史
      - name: Check formatting for PR files
        run: |
          bash scripts/ci_python_black.sh
